### ISSUE TITLE
Variable Fonts issue in Adobe apps? 

### ISSUE THREAD

**Issue by davelab6** [theleagueof/league-spartan#14]
A user wrote me,

> Dear Google Fonts,
> 
> I noticed that one of your variable fonts have an error, specifically Spartan Variable.
> https://t.co/IvVmVJZ2KZ
> 
> The normal non-variable Spartan set is fine, but the variable has an issues where the character "u" and it's alternatives (like ú, ü, ű etc.) are too high compared to other characters. This happens from weights 501 to 899. The 500 (medium) and 900 (black) are fine, but the ones between them are incorrectly sized.
> 
> It's weird, because the preview on your website and in a font manager software this doesn't occur, the font looks absolutely fine. This issue comes alive only when i actually use the font in Adobe Illustrator or Photoshop. Haven't tried other software tho, but other variable fonts work fine.
> 
> I don't know how much control you have, considering it's made by someone else outside of Google i assume, but i hope you can fix this. Thanks!

**Comment by alerque** [comment]
@sursly At least until I have more tooling spun up for this, this is probably going to have to be your domain. Any idea what's up?

**Comment by sursly** [comment]
This isn't my version of League Spartan variable, so I have no clue. Didn't even know there was a Spartan on Google Fonts.

**Comment by alerque** [comment]
Oh. So we had _two_ forks of League Spartan sporting VF floating around. Spiffy.

@davelab6 What's the source on the one Google Fonts has posted?

**Comment by sursly** [comment]
In looking at the source, I think this version has fontlab source files (from the UFOs?), which would make it very different from the one I pushed out.

**Comment by alerque** [comment]
This issue report seems to be for a completely different font project. The "Spartan" and "Spartan Variable" fonts on Google fonts are from [this repository](https://github.com/bghryct/Spartan-MB) originally by Matt Bailey and extended by Mirko Velimirovic. As far as I can tell this is a completely different project that just happens to share a similar name. If they used "League Spartan" as a starting point I don't even see that credited anywhere.

There is at least one [other project](https://github.com/MircoMonsees/League-Spartan-Italic) that *did* start as a fork from League Spartan that converted it to a variable font independencly from Tyler's work, but that also seems unrelated to the Spartan on Google Fonts.

I'm closing this as an invalid report, but @davelab6 of course we'd be interested in seeing an actual League Spartan release on Google Fonts. If that's in the cards lets make it the topic for a new issue.
