### ISSUE TITLE
Why is stylesheet.css marked executable?

### ISSUE THREAD

**Issue by stuartpb** [theleagueof/league-spartan#2]
Is there a reason `_webfonts/stylesheet.css` is `chmod +x`?

**Comment by alerque** [comment]
Good point. It shouldn't be. We'll fix that in an upcoming re-arrangement of this repository and the release process.

**Comment by alerque** [comment]
I believe this issue is obsolete now. The modern releases of this font only include WOFF fonts for web work; the SVG fonts and matching CSS tricks have been completely deprecated.
