### ISSUE TITLE
Weight axis issue building with new gftools

### ISSUE THREAD

**Issue by alerque** [theleagueof/league-spartan#29]
I think we ran into this on Raleway too, but one of the things we're doing as part of Fontship’s build process is using the normalization and fixup tools in `gftools` (Google Fonts' toolkit). It has gotten a little bit stricter since we released v2.210. If still builds with the old Docker image of Fontship (v0.3.4), but trying to upgrade it to anything newer (such as the current v0.5.0 or `master` branch) fails:

```
File "/usr/bin/gftools-fix-vf-meta.py", line 167, in update_nametable
raise ValueError(f"Unsupported wght coord '{wght_val}'. Coord "
ValueError: Unsupported wght coord '277.0'. Coord needs to be in {WGHT.keys()}
```

**Comment by alerque** [comment]
Hmm, it wasn't Raleway, it was *this* font and it [came up here](https://github.com/theleagueof/league-spartan/pull/20).

**Comment by alerque** [comment]
This has something to do with this:

https://github.com/theleagueof/league-spartan/blob/4b19a40ba3b8bdc312c5115b22203fbf19410aa2/sources/LeagueSpartan.glyphs#L56-L70

If I make the two oddball mappings here `200 = 200` and `400 = 400` everything builds fine. I can't (yet) find another combination of values or way to work around this.

**Comment by alerque** [comment]
Clearly my hack to make this work before wasn't the *right* solution. This was discussed at length in [this glyphsLib](https://github.com/googlefonts/glyphsLib/issues/568) issue. I'm still not sure what the right fix is here, but links from that discussion should help.

**Comment by alerque** [comment]
Arg! This is **not** right. It builds fine, but some experimenting with the static instances as generated now show that they are *not* an even map now. In v2.210 this was a straight line, now it's not:

![image](https://user-images.githubusercontent.com/173595/97222407-6be13800-17df-11eb-9d64-96211d6c5319.png)

@sursly Can you take a look at this again? The hack I made on the Glyphs source before no longer builds using the latest tooling (`fontmake` + `gftools`), which is now the current tooling inside `fontship`. I've swapped out that hack for another one that now builds again, but given the output above I'm pretty sure it's actually broken. Can you branch off the current master and have a look at this is Glyphs again? Given the discussion I saw between Glyphs developers and Google I suspect the output of Glyphs might actually have changed so that these all work together now, but the sources for this font need fixing so your weight axis adjustment works as intended.

**Comment by alerque** [comment]
For reference the old hack revert is at 243cd9e and the new hack I added is ad13b58. If you want to get back to the original without either of my hacks and work from there, `git revert ad13b58` will get you there.

**Comment by alerque** [comment]
I've taken another stab at fixing this myself, see #31.

**Comment by sursly** [comment]
OK, using the latest gftools and fontmake, my version builds fine 👍 I did normalize the weight values for the instances so they are linear (as you did in #31 ) and properly indicate that 900 is black. Think we can close this and I'll see you in the other issue.
