### ISSUE TITLE
hairspace character rendering incorrectly

### ISSUE THREAD

**Issue by jbullock35** [theleagueof/league-spartan#42]
It looks as though the hairspace character (U+200A) in League Spartan is much wider than a normal hairspace, and its width is causing problems for [Standard Ebooks](https://standardebooks.org/). Details and screenshots are at https://github.com/standardebooks/ford-madox-ford_some-do-not/issues/6.

If the hairspace character really is wider than a normal hairspace, can it be fixed in a future release?

**Comment by kenmcd** [comment]
League Spartan does not have a hairspace character (`2026`).
So what you are seeing is a fallback font.

> Typically it renders the same width as the spaces between the dots. It's our house style to include a hair space before all ellipses.

That is dumb.
And not needed with quality text fonts (with proper ellipsis).
Sounds like a work-around for their bad fonts.

Not likely hairspace is going to get added here any time soon.
So your best bet is to simply fix epub the text.

**Comment by jbullock35** [comment]
Thank you, @kenmcd. All good to know.
