### ISSUE TITLE
SVG ID is wrong in the CSS

### ISSUE THREAD

**Issue by a-koka** [theleagueof/league-spartan#6]
Shouldn't the CSS refer to the SVG font id as `league_spartanregular` instead of `league_spartanbold`?

**Comment by chronodm** [comment]
I'm not a typographer, but if you compare with, say, Futura, League Spartan is pretty clearly bold.
![screen shot 2018-02-09 at 3 38 27 pm](https://user-images.githubusercontent.com/2934647/36055161-5b397f0e-0daf-11e8-8918-7f8751731d67.png)

**Comment by a-koka** [comment]
I'm not debating the name here @chronodm. `stylesheet.css` refers to the font as `league_spartanbold` but the SVG has the font id set as `league_spartanregular`.

That's all!

**Comment by alerque** [comment]
I believe this issue is obsolete now. The modern releases of this font only include WOFF fonts for web work; the SVG fonts and matching CSS tricks have been completely deprecated.
