### ISSUE TITLE
State of additional weights?

### ISSUE THREAD

**Issue by jacobq** [theleagueof/league-spartan#8]
From [the home page](https://www.theleagueofmoveabletype.com/league-spartan):
> Taking a strong influence from ATF's classic Spartan family, we're starting our own family out with a single strong weight. We've put a few unique touches into a beautiful, historical typeface, and made sure to include an extensive characterset – currently totaling over 300 glyphs.

> Over time, the open-source license will allow us **expand League Spartan into a full family, with multiple weights and styles**, and we're starting by releasing our first Bold style for this exciting, modern classic now.

Has there been any progress on this? Is there a way I could make a small monetary contribution to support this work? I would really like to get a normal weight version.

See also https://github.com/theleagueof/league-spartan/issues/7

**Comment by Xylobol** [comment]
Here's a notable fork: https://github.com/fredrikhemsen/leaguespartan

**Comment by micahbrich** [comment]
Update @jacobq @Xylobol — long time coming obviously, and I appreciate the offer a lot. I think if I were not such an awful repo maintainer I'd have done a better job of this a long long time ago, but we _just_ pulled in Tyler's extra weights + variable version. 🙌 I'm sure it's far too late for where you were a year ago, but maybe it'll still be useful now!

**Comment by jacobq** [comment]
It is definitely still useful; thank you! :heart:
